2021/09/03 10:04:17 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:4586"
2021/09/03 10:04:17 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:4586"
2021/09/03 10:06:25 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:06:25 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:06:27 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:06:27 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:07:13 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.html HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:07:13 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.html HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:08:09 [error] 25#25: *2 open() "/home/work/ceportal/public/index.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /index.html HTTP/1.1", host: "127.0.0.1:4586"
2021/09/03 10:08:09 [error] 25#25: *2 open() "/home/work/ceportal/public/error/404.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /index.html HTTP/1.1", host: "127.0.0.1:4586"
2021/09/03 11:56:55 [error] 25#25: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 11:56:55 [error] 25#25: *4 open() "/home/work/ceportal/public/error/502.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 11:57:37 [error] 25#25: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 11:57:37 [error] 25#25: *4 open() "/home/work/ceportal/public/error/502.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 12:00:00 [error] 25#25: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /health.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 12:00:00 [error] 25#25: *7 open() "/home/work/ceportal/public/error/502.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /health.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 04:19:57 [error] 25#25: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /health.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 04:19:57 [error] 25#25: *11 open() "/home/work/ceportal/public/error/502.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /health.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 04:21:58 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 04:21:58 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 19:03:04 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/"
2021/09/04 19:03:04 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/"
2021/09/04 19:03:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:06:31 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:06:31 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:06:31 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:06:31 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:06:48 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:06:48 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:06:48 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:06:48 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/06 01:41:03 [error] 24#24: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586", referrer: "http://appgm74odym2071.h5.xiaoeknow.com:4586/"
2021/09/06 01:41:24 [error] 24#24: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586", referrer: "http://appgm74odym2071.h5.xiaoeknow.com:4586/"
2021/09/06 01:43:03 [error] 27#27: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:43:24 [error] 27#27: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:44:32 [error] 27#27: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:44:53 [error] 27#27: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:46:11 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:46:32 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 09:07:44 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:07:44 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:08:36 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:08:36 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:08:38 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:08:38 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:14:59 [error] 33#33: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 127.0.0.1:10010 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:44:07 [error] 26#26: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 127.0.0.1:10010 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 10:00:35 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 10:02:57 [error] 27#27: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 0.0.0.0:10010 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 10:04:02 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 10:04:02 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 01:47:07 [error] 26#26: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/07 01:48:11 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 01:49:11 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 01:57:31 [error] 26#26: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/07 01:59:02 [error] 26#26: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:00:16 [error] 26#26: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:01:16 [error] 26#26: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:05:15 [error] 26#26: *17 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:06:15 [error] 26#26: *17 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:17:41 [error] 26#26: *22 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:18:41 [error] 26#26: *22 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 04:56:44 [error] 26#26: *26 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 04:58:02 [error] 26#26: *32 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 04:59:02 [error] 26#26: *32 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:03:44 [error] 26#26: *36 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:03:46 [error] 26#26: *36 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 06:10:27 [error] 26#26: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:11:27 [error] 26#26: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:21:27 [error] 26#26: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:22:27 [error] 26#26: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:24:04 [error] 26#26: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:25:04 [error] 26#26: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:42:02 [error] 26#26: *52 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:43:02 [error] 26#26: *52 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 07:04:04 [error] 26#26: *57 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 07:05:04 [error] 26#26: *57 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 07:23:12 [error] 26#26: *60 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 07:23:15 [error] 26#26: *60 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 09:50:25 [error] 26#26: *64 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 09:50:27 [error] 26#26: *64 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 10:27:19 [error] 27#27: *69 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 10:27:21 [error] 27#27: *69 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 11:39:20 [error] 26#26: *73 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 11:39:23 [error] 26#26: *73 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 11:52:57 [error] 26#26: *77 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 11:53:00 [error] 26#26: *77 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:09:50 [error] 27#27: *80 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:09:52 [error] 27#27: *80 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:37:39 [error] 26#26: *85 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:37:41 [error] 26#26: *85 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:43:14 [error] 26#26: *88 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:43:17 [error] 26#26: *88 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:49:51 [error] 26#26: *92 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:49:54 [error] 26#26: *92 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:53:35 [error] 26#26: *96 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:53:37 [error] 26#26: *96 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:55:42 [error] 26#26: *96 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:55:44 [error] 26#26: *96 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/08 01:49:33 [error] 26#26: *104 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 01:49:35 [error] 26#26: *104 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 02:29:56 [error] 26#26: *108 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 02:29:59 [error] 26#26: *108 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 03:32:09 [error] 27#27: *112 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 03:32:11 [error] 27#27: *112 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 06:07:02 [error] 26#26: *115 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 06:07:05 [error] 26#26: *115 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 06:22:58 [error] 26#26: *120 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 06:23:00 [error] 26#26: *120 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 06:46:34 [error] 26#26: *124 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 06:46:36 [error] 26#26: *124 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 07:09:35 [error] 26#26: *128 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 07:09:37 [error] 26#26: *128 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 07:25:12 [error] 26#26: *131 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 07:25:14 [error] 26#26: *131 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 07:34:44 [error] 26#26: *135 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 07:34:46 [error] 26#26: *135 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 07:35:58 [error] 26#26: *135 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 07:35:59 [error] 26#26: *135 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 07:55:52 [error] 26#26: *142 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 07:55:55 [error] 26#26: *142 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 08:02:33 [error] 27#27: *147 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:03:33 [error] 27#27: *147 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:06:39 [error] 26#26: *152 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:08:38 [error] 26#26: *152 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:09:38 [error] 26#26: *152 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:19:40 [error] 26#26: *159 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:20:40 [error] 26#26: *159 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:25:10 [error] 26#26: *164 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:26:10 [error] 26#26: *164 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:34:26 [error] 27#27: *168 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:35:26 [error] 27#27: *168 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:56:54 [error] 26#26: *173 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 08:57:54 [error] 26#26: *173 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 09:26:47 [error] 26#26: *176 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 09:26:49 [error] 26#26: *176 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 09:34:23 [error] 27#27: *180 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 09:34:26 [error] 27#27: *180 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 09:42:06 [error] 26#26: *184 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 09:42:09 [error] 26#26: *184 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/08 09:43:19 [error] 26#26: *184 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/08 09:43:20 [error] 26#26: *184 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Bo
2021/09/09 05:00:24 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "POST /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/09 05:00:26 [error] 25#25: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/09 05:01:58 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "POST /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/09 05:01:59 [error] 25#25: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/09 05:03:39 [error] 25#25: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/09 05:04:10 [error] 25#25: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/09 05:05:22 [error] 25#25: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "POST /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/09 05:06:22 [error] 25#25: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "POST /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/09 05:10:49 [error] 25#25: *14 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "POST /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/09 05:11:30 [error] 25#25: *14 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/data/exception/ceportal/ceportal_2021-09-09.exception.log" could not be opened: failed to open stream: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#4 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/ExceptionReporter.php(197): Monolog\Logger->error('{"log_at":"2021...')
#5 /home/work/ceportal...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 107, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/09 07:16:13 [error] 25#25: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/data/exception/ceportal/ceportal_2021-09-09.exception.log" could not be opened: failed to open stream: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#4 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/ExceptionReporter.php(197): Monolog\Logger->error('{"log_at":"2021...')
#5 /home/work/ceportal...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 107, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/09 07:16:53 [error] 25#25: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/data/exception/ceportal/ceportal_2021-09-09.exception.log" could not be opened: failed to open stream: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#4 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/ExceptionReporter.php(197): Monolog\Logger->error('{"log_at":"2021...')
#5 /home/work/ceportal...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 107, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/09 07:18:29 [error] 25#25: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: The stream or file "/data/exception/ceportal/ceportal_2021-09-09.exception.log" could not be opened: failed to open stream: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:107
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#4 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/ExceptionReporter.php(197): Monolog\Logger->error('{"log_at":"2021...')
#5 /home/work/ceportal...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 107, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/09 07:19:34 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 07:20:34 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 07:35:45 [error] 25#25: *13 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 07:36:45 [error] 25#25: *13 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 08:46:19 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 08:47:19 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 08:49:00 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 08:50:00 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 08:52:38 [error] 25#25: *7 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 08:53:38 [error] 25#25: *7 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:18:05 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:22:08 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:24:08 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:25:08 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:27:29 [error] 25#25: *12 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:28:29 [error] 25#25: *12 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:30:39 [error] 25#25: *15 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:31:39 [error] 25#25: *15 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.18.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.18.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:41:56 [error] 31#31: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 09:42:56 [error] 31#31: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 10:52:22 [error] 25#25: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 13:00:41 [error] 32#32: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 13:10:43 [error] 32#32: *6 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 13:11:43 [error] 32#32: *6 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 13:14:56 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 13:16:17 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/09 13:17:17 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:08:18 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:10:47 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:11:47 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:13:17 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:14:17 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:15:36 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:16:36 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:17:46 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:18:46 [error] 26#26: *8 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:22:03 [error] 26#26: *32 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:23:18 [error] 26#26: *35 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:24:18 [error] 26#26: *35 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:26:57 [error] 26#26: *35 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:27:58 [error] 26#26: *35 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:29:29 [error] 26#26: *35 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:30:29 [error] 26#26: *35 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:39:57 [error] 26#26: *43 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:41:44 [error] 26#26: *43 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:42:44 [error] 26#26: *43 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:47:29 [error] 26#26: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:48:29 [error] 26#26: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:50:36 [error] 26#26: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:52:18 [error] 26#26: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:53:18 [error] 26#26: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:54:35 [error] 26#26: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:55:35 [error] 26#26: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:58:33 [error] 26#26: *60 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 02:59:52 [error] 26#26: *60 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 03:00:52 [error] 26#26: *60 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 03:28:30 [error] 26#26: *65 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 03:29:31 [error] 26#26: *65 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 03:33:12 [error] 26#26: *74 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 03:35:11 [error] 26#26: *74 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 03:36:11 [error] 26#26: *74 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 03:39:07 [error] 26#26: *74 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 03:40:07 [error] 26#26: *74 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 04:14:30 [error] 26#26: *82 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 04:17:01 [error] 26#26: *82 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 04:18:01 [error] 26#26: *82 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:09:17 [error] 26#26: *88 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:11:24 [error] 26#26: *88 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:12:34 [error] 26#26: *88 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:13:34 [error] 26#26: *88 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:15:57 [error] 26#26: *98 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:16:57 [error] 26#26: *98 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:20:27 [error] 26#26: *101 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:21:27 [error] 26#26: *101 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:26:38 [error] 26#26: *106 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:27:38 [error] 26#26: *106 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:36:04 [error] 26#26: *112 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:37:04 [error] 26#26: *112 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:44:55 [error] 26#26: *115 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:46:55 [error] 26#26: *115 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:47:55 [error] 26#26: *115 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:50:16 [error] 26#26: *123 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:51:38 [error] 26#26: *123 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 06:52:38 [error] 26#26: *123 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 07:09:18 [error] 26#26: *130 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 07:10:18 [error] 26#26: *130 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 07:33:36 [error] 26#26: *133 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 07:34:36 [error] 26#26: *133 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 07:42:38 [error] 26#26: *136 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 07:43:38 [error] 26#26: *136 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 07:49:14 [error] 26#26: *139 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 07:50:14 [error] 26#26: *139 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 08:07:42 [error] 26#26: *146 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 08:08:42 [error] 26#26: *146 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 08:46:07 [error] 26#26: *149 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 08:47:07 [error] 26#26: *149 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:02:07 [error] 26#26: *152 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:03:07 [error] 26#26: *152 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:05:52 [error] 26#26: *155 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:06:53 [error] 26#26: *155 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:16:40 [error] 26#26: *158 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:17:41 [error] 26#26: *158 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:21:22 [error] 26#26: *162 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:22:22 [error] 26#26: *162 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:30:14 [error] 26#26: *168 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:31:14 [error] 26#26: *168 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:40:30 [error] 26#26: *171 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:41:30 [error] 26#26: *171 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:55:18 [error] 26#26: *174 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:57:28 [error] 26#26: *174 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 09:58:28 [error] 26#26: *174 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 10:01:07 [error] 26#26: *174 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 10:03:02 [error] 26#26: *174 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/10 10:04:02 [error] 26#26: *174 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/11 03:16:45 [error] 26#26: *185 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/11 03:20:20 [error] 26#26: *188 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/11 03:21:54 [error] 26#26: *188 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/11 04:12:55 [error] 26#26: *193 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/11 04:49:46 [error] 26#26: *196 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/11 05:20:57 [error] 26#26: *199 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/11 05:22:01 [error] 26#26: *199 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 02:57:27 [error] 26#26: *204 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 03:02:21 [error] 26#26: *207 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 03:06:41 [error] 26#26: *210 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 03:08:03 [error] 26#26: *210 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 03:09:03 [error] 26#26: *210 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 03:25:54 [error] 26#26: *216 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 03:26:54 [error] 26#26: *216 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 04:16:10 [error] 26#26: *219 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 04:19:55 [error] 26#26: *222 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 04:26:57 [error] 26#26: *225 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 09:47:16 [error] 26#26: *228 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 11:41:36 [error] 26#26: *231 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 11:44:47 [error] 26#26: *234 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 11:48:54 [error] 26#26: *237 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 11:57:31 [error] 26#26: *240 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 12:00:27 [error] 26#26: *246 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 12:01:27 [error] 26#26: *246 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 12:08:33 [error] 26#26: *249 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 12:09:33 [error] 26#26: *249 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:02:11 [error] 26#26: *254 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:03:11 [error] 26#26: *254 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:05:15 [error] 26#26: *254 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:07:09 [error] 26#26: *254 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:08:09 [error] 26#26: *254 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:19:35 [error] 26#26: *262 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:20:35 [error] 26#26: *262 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:26:41 [error] 26#26: *265 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:28:06 [error] 26#26: *265 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:29:06 [error] 26#26: *265 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:50:34 [error] 26#26: *279 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:52:28 [error] 26#26: *279 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 13:53:29 [error] 26#26: *279 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 18:47:34 [error] 26#26: *284 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 18:49:13 [error] 26#26: *284 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 18:54:33 [error] 26#26: *289 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 18:58:21 [error] 26#26: *292 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 19:00:22 [error] 26#26: *292 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 19:02:42 [error] 26#26: *292 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 19:16:11 [error] 26#26: *299 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 19:19:36 [error] 26#26: *302 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/12 19:20:36 [error] 26#26: *302 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:02:02 [error] 25#25: *35 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:03:02 [error] 25#25: *35 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/pre_get_info/v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:09:39 [error] 25#25: *42 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:11:29 [error] 25#25: *42 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:13:10 [error] 25#25: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:14:10 [error] 25#25: *50 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:23:14 [error] 25#25: *53 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:24:14 [error] 25#25: *53 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:32:53 [error] 25#25: *58 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:33:53 [error] 25#25: *58 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:46:02 [error] 25#25: *61 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 05:47:02 [error] 25#25: *61 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 06:31:27 [error] 25#25: *64 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 07:38:01 [error] 25#25: *67 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 07:40:18 [error] 25#25: *70 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 07:59:23 [error] 25#25: *73 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:05:22 [error] 25#25: *76 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:07:49 [error] 25#25: *79 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:26:13 [error] 25#25: *82 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:27:41 [error] 25#25: *82 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:28:41 [error] 25#25: *82 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:44:41 [error] 25#25: *89 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:45:41 [error] 25#25: *89 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:48:24 [error] 25#25: *92 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
2021/09/14 08:49:24 [error] 25#25: *92 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.20.0.1, server: appv9qcdqdl1290.local.com, request: "POST /pay/get_info?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.20.0.2:9000", host: "appv9qcdqdl1290.local.com"
