2021/09/03 10:04:17 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:4586"
2021/09/03 10:04:17 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "127.0.0.1:4586"
2021/09/03 10:06:25 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:06:25 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:06:27 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:06:27 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET / HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:07:13 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.html HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:07:13 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.html HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "127.0.0.1:4586"
2021/09/03 10:08:09 [error] 25#25: *2 open() "/home/work/ceportal/public/index.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /index.html HTTP/1.1", host: "127.0.0.1:4586"
2021/09/03 10:08:09 [error] 25#25: *2 open() "/home/work/ceportal/public/error/404.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /index.html HTTP/1.1", host: "127.0.0.1:4586"
2021/09/03 11:56:55 [error] 25#25: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 11:56:55 [error] 25#25: *4 open() "/home/work/ceportal/public/error/502.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 11:57:37 [error] 25#25: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 11:57:37 [error] 25#25: *4 open() "/home/work/ceportal/public/error/502.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 12:00:00 [error] 25#25: *7 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /health.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/03 12:00:00 [error] 25#25: *7 open() "/home/work/ceportal/public/error/502.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /health.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 04:19:57 [error] 25#25: *11 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /health.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 04:19:57 [error] 25#25: *11 open() "/home/work/ceportal/public/error/502.html" failed (2: No such file or directory), client: 172.21.0.1, server: , request: "GET /health.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 04:21:58 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 04:21:58 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: , request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/04 19:03:04 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/"
2021/09/04 19:03:04 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/"
2021/09/04 19:03:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:17 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:32 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:03:33 [error] 25#25: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:06:31 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:06:31 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:06:31 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:06:31 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:06:48 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:06:48 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586"
2021/09/04 19:06:48 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/04 19:06:48 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.21.0.1, server: a.h5_ceportal.xiaoe.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "a.h5_ceportal.xiaoe.com:4586", referrer: "http://a.h5_ceportal.xiaoe.com:4586/index.php"
2021/09/06 01:41:03 [error] 24#24: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586", referrer: "http://appgm74odym2071.h5.xiaoeknow.com:4586/"
2021/09/06 01:41:24 [error] 24#24: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /favicon.ico HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586", referrer: "http://appgm74odym2071.h5.xiaoeknow.com:4586/"
2021/09/06 01:43:03 [error] 27#27: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:43:24 [error] 27#27: *4 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:44:32 [error] 27#27: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:44:53 [error] 27#27: *9 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:46:11 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 01:46:32 [error] 24#24: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.18.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.21.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com:4586"
2021/09/06 09:07:44 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:07:44 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:08:36 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:08:36 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:08:38 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:08:38 [error] 25#25: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:14:59 [error] 33#33: *11 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 127.0.0.1:10010 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 09:44:07 [error] 26#26: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 127.0.0.1:10010 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 10:00:35 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 10:02:57 [error] 27#27: *2 FastCGI sent in stderr: "PHP message: Xdebug: [Step Debug] Could not connect to debugging client. Tried: 0.0.0.0:10010 (through xdebug.client_host/xdebug.client_port) :-(" while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 10:04:02 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/06 10:04:02 [error] 26#26: *2 connect() failed (111: Connection refused) while connecting to upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /index.php?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.3:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 01:47:07 [error] 26#26: *1 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/07 01:48:11 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 01:49:11 [error] 26#26: *1 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 01:57:31 [error] 26#26: *9 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boot
2021/09/07 01:59:02 [error] 26#26: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:00:16 [error] 26#26: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:01:16 [error] 26#26: *9 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:05:15 [error] 26#26: *17 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:06:15 [error] 26#26: *17 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:17:41 [error] 26#26: *22 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 02:18:41 [error] 26#26: *22 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 04:56:44 [error] 26#26: *26 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 04:58:02 [error] 26#26: *32 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 04:59:02 [error] 26#26: *32 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:03:44 [error] 26#26: *36 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:03:46 [error] 26#26: *36 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 06:10:27 [error] 26#26: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:11:27 [error] 26#26: *39 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:21:27 [error] 26#26: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:22:27 [error] 26#26: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:24:04 [error] 26#26: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:25:04 [error] 26#26: *44 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:42:02 [error] 26#26: *52 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 06:43:02 [error] 26#26: *52 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 07:04:04 [error] 26#26: *57 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 07:05:04 [error] 26#26: *57 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 07:23:12 [error] 26#26: *60 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 07:23:15 [error] 26#26: *60 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 09:50:25 [error] 26#26: *64 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 09:50:27 [error] 26#26: *64 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 10:27:19 [error] 27#27: *69 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 10:27:21 [error] 27#27: *69 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 11:39:20 [error] 26#26: *73 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 11:39:23 [error] 26#26: *73 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 11:52:57 [error] 26#26: *77 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 11:53:00 [error] 26#26: *77 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:09:50 [error] 27#27: *80 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:09:52 [error] 27#27: *80 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:37:39 [error] 26#26: *85 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:37:41 [error] 26#26: *85 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:43:14 [error] 26#26: *88 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:43:17 [error] 26#26: *88 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:49:51 [error] 26#26: *92 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:49:54 [error] 26#26: *92 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:53:35 [error] 26#26: *96 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:53:37 [error] 26#26: *96 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
2021/09/07 12:55:42 [error] 26#26: *96 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 172.19.0.1, server: appgm74odym2071.h5.xiaoeknow.com, request: "GET /pay/pre_get_info_v3?XDEBUG_SESSION_START=qqq HTTP/1.1", upstream: "fastcgi://172.19.0.2:9000", host: "appgm74odym2071.h5.xiaoeknow.com"
2021/09/07 12:55:44 [error] 26#26: *96 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught UnexpectedValueException: There is no existing directory at "/data/exception/ceportal" and its not buildable: Permission denied in /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php:161
Stack trace:
#0 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/StreamHandler.php(97): Monolog\Handler\StreamHandler->createDir()
#1 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/RotatingFileHandler.php(106): Monolog\Handler\StreamHandler->write(Array)
#2 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Handler/AbstractProcessingHandler.php(37): Monolog\Handler\RotatingFileHandler->write(Array)
#3 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(336): Monolog\Handler\AbstractProcessingHandler->handle(Array)
#4 /home/work/ceportal/vendor/monolog/monolog/src/Monolog/Logger.php(615): Monolog\Logger->addRecord(400, '{"log_at":"2021...', Array)
#5 /home/work/ceportal/vendor/xiaoe/exception-reporter/src/Ex...
PHP message: PHP Fatal error:  Uncaught ErrorException: Function must be enabled in php.ini by setting 'xdebug.mode' to 'develop' in /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php:35
Stack trace:
#0 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(2, 'Function must b...', '/home/work/cepo...', 35, Array)
#1 /home/work/ceportal/vendor/symfony/debug/Exception/FatalErrorException.php(35): xdebug_get_function_stack()
#2 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(132): Symfony\Component\Debug\Exception\FatalErrorException->__construct('Uncaught Unexpe...', 1, 0, '/home/work/cepo...', 161, 0)
#3 /home/work/ceportal/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(118): Illuminate\Foundation\Bootstrap\HandleExceptions->fatalExceptionFromError(Array, 0)
#4 [internal function]: Illuminate\Foundation\Boo
